# Версия для разработки
version: '3.5'

services:
  minio:
    hostname: minio1
    image: minio/minio:latest
    restart: always
    command: server --address :10123 --console-address ":10124" /data/minio
    expose:
      - "10123"
      - "10124"
    ports:
      - "10123:10123"
      - "10124:10124"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./data:/data

  files-storage:
    image: nginx:alpine
    restart: always
    ports:
      - "10589:80"
    expose:
      - "80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro